//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translations {


    public partial class Admin {

        /// <summary>
        /// head control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// litUserInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserInitials;

        /// <summary>
        /// litUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>
        /// litUserRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserRole;

        /// <summary>
        /// liTranslators control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTranslators;

        /// <summary>
        /// navTranslators control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTranslators;

        /// <summary>
        /// liCountries control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCountries;

        /// <summary>
        /// navCountries control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navCountries;

        /// <summary>
        /// liLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLanguages;

        /// <summary>
        /// navLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navLanguages;

        /// <summary>
        /// liCountryLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCountryLanguages;

        /// <summary>
        /// navCountryLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navCountryLanguages;

        /// <summary>
        /// liTranslatorLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTranslatorLanguages;

        /// <summary>
        /// navTranslatorLanguages control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTranslatorLanguages;

        /// <summary>
        /// liTranslationKeys control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTranslationKeys;

        /// <summary>
        /// navTranslationKeys control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTranslationKeys;

        /// <summary>
        /// liTranslations control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTranslations;

        /// <summary>
        /// navTranslations control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTranslations;

        /// <summary>
        /// liTranslatorTranslations control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTranslatorTranslations;

        /// <summary>
        /// navTranslatorTranslations control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTranslatorTranslations;

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
