//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translations {


    public partial class Countries {

        /// <summary>
        /// divAddEdit control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAddEdit;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// RequiredFieldValidator1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        /// <summary>
        /// txtISONumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtISONumber;

        /// <summary>
        /// txtISOCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtISOCode;

        /// <summary>
        /// RequiredFieldValidator2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        /// <summary>
        /// txtShortCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtShortCode;

        /// <summary>
        /// chkActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// diverror control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl diverror;

        /// <summary>
        /// divCountries control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCountries;

        /// <summary>
        /// btnAddNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAddNew;

        /// <summary>
        /// gvCountries control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCountries;
    }
}
