//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translations {


    public partial class ResourceGenerator {

        /// <summary>
        /// ddlCountryLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCountryLanguage;

        /// <summary>
        /// txtFilePrefix control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilePrefix;

        /// <summary>
        /// chkIncludeEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIncludeEmpty;

        /// <summary>
        /// btnDownloadLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDownloadLanguage;

        /// <summary>
        /// txtGlobalFileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGlobalFileName;

        /// <summary>
        /// btnDownloadGlobal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDownloadGlobal;

        /// <summary>
        /// btnDownloadAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDownloadAll;

        /// <summary>
        /// gvStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvStats;
    }
}
