//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryLanguages = new HashSet<CountryLanguage>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string ISONumber { get; set; }
        public string ISOCode { get; set; }
        public string ShortCode { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual ICollection<CountryLanguage> CountryLanguages { get; set; }
    }
}
