//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryLanguage
    {
        public CountryLanguage()
        {
            this.TranslatorCountryLanguages = new HashSet<TranslatorCountryLanguage>();
            this.Translations = new HashSet<Translation>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long CountryId { get; set; }
        public long LanguageId { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<TranslatorCountryLanguage> TranslatorCountryLanguages { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
