//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationKey
    {
        public TranslationKey()
        {
            this.Translations = new HashSet<Translation>();
        }
    
        public long Id { get; set; }
        public string Key { get; set; }
        public string EnglishValue { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public long TranslatorId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
