//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public long Id { get; set; }
        public long TranslationKeyId { get; set; }
        public Nullable<long> TranslatorId { get; set; }
        public Nullable<long> CountryLanguageId { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Translated { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual CountryLanguage CountryLanguage { get; set; }
        public virtual TranslationKey TranslationKey { get; set; }
    }
}
