//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translator
    {
        public Translator()
        {
            this.TranslationKeys = new HashSet<TranslationKey>();
            this.TranslatorCountryLanguages = new HashSet<TranslatorCountryLanguage>();
        }
    
        public long Id { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public bool Active { get; set; }
        public string MobileNumber { get; set; }
        public string PhotoURL { get; set; }
        public string Role { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual ICollection<TranslationKey> TranslationKeys { get; set; }
        public virtual ICollection<TranslatorCountryLanguage> TranslatorCountryLanguages { get; set; }
    }
}
